name: CICD Font-end

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

   
    steps:
    - uses: actions/checkout@v2
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: build docker images
      run: |
        docker build . --tag ghcr.io/int222-025-067-127/front-end
        docker images 
    - name: push docker image to registy
      run: |
       docker push ghcr.io/int222-025-067-127/front-end
        
  deploy:
    needs: build
    runs-on: ubuntu-latest  
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
              export CR_PAT=${{ secrets.GITHUB_TOKEN }}
              echo $CR_PAT | sudo docker login ghcr.io -u nattanunkorn9743 --password-stdin
              sudo docker rmi int222-025-067-127/front-end:latest
              sudo docker pull ghcr.io/int222-025-067-127/front-end:latest
              sudo docker images
              sudo docker-compose -f ~/docker-compose.yml down
              sudo docker-compose -f ~/docker-compose.yml up -d
#    deploy:
#     - name: executing remote ssh commands using password
#       uses: appleboy/ssh-action@master
#       with:
#        host: ${{ secrets.HOST }}
#        username: ${{ secrets.USERNAME }}
#        password: ${{ secrets.PASSWORD }}
#        port: ${{ secrets.PORT }}
#        script: |
#         export CR_PAT=${{ secrets.GITHUB.TOKEN }}
 
    
      
