name: Font-End
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# env:
#   AZURE_WEBAPP_NAME: int222-project-backend   # set this to your application's name
#   AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
#   NODE_VERSION: '14.17.6'                # set this to the node version to 

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
#     environment: production

    steps:
    - uses: actions/checkout@v2
    

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}   
    - name: build image
      run: |
          docker build . --tag ghcr.io/nattanunkorn9743/int222-025-067-127/front-end
          docker image
    - name: push to registry
      run: |
          docker push ghcr.io/nattanunkorn9743/int222-025-067-127/front-end
          
#    deploy:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
       host: ${{ secrets.HOST }}
       username: ${{ secrets.USERNAME }}
       password: ${{ secrets.PASSWORD }}
       port: ${{ secrets.PORT }}
       script: |
        export CR_PAT=${{ secrets.GITHUB.TOKEN }}
 
    
      
