name: CICD Font-end

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

   
    steps:
    - uses: actions/checkout@v2
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    - name: build docker images
      run: |
        docker build . --tag ghcr.io/int222-025-067-127/front-end
        docker images 
    - name: push docker image to registy
      run: |
       docker push ghcr.io/int222-025-067-127/front-end
        
  deploy:
    needs: build
    runs-on: ubuntu-latest  
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: 20.205.233.130
          username: 'int222project'
          password: 'Cake.1234567890'
          port: 22
          script: |
              ls
              export CR_PAT=${{ secrets.GITHUB_TOKEN }}
              echo $CR_PAT | sudo docker login ghcr.io -u nattanunkorn9743 --password-stdin
              sudo docker pull ghcr.io/int222-025-067-127/front-end:latest
              sudo docker images
              sudo docker rm front-end -f
              sudo docker run -p 3000:3000 -d --name front-end ghcr.io/int222-025-067-127/front-end:latest
              sudo docker ps
              
 
    
      
